### ISSUE TITLE
There is a new release

### ISSUE THREAD

**Issue by libreajans** [flathub/org.soundconverter.SoundConverter#12]
Hi, there is a new SoundConverter release: 4.0.3

It may help some people.

https://github.com/kassoulet/soundconverter/tags
https://git.launchpad.net/soundconverter/log/

**Comment by jmaibaum** [comment]
Hi,

SoundConverter v4.0.3 is available via Flathub already.

If you still have an older version installed, please try running `flatpak update` or search for updates in your graphical software manager.

**Comment by libreajans** [comment]
You are correct. I wasn't sure because Flathub says its version is "4.0.0"

https://flathub.org/apps/details/org.soundconverter.SoundConverter

It's 4.0.3 on About SoundConverter dialog.

![Ekran Görüntüsü - 2022-08-26 21-25-56](https://user-images.githubusercontent.com/6218679/186968516-882f45c6-3131-4bed-b1bc-ecd5efb4e79a.png)

**Comment by libreajans** [comment]
Ok, I found that new releases hasn't been added to appdata.xml

Due to appdata says its version is 4.0.0 it has been shown this way.

https://github.com/kassoulet/soundconverter/blob/main/data/soundconverter.appdata.xml

**Comment by jmaibaum** [comment]
Since `appstream.xml` is maintained upstream, there is nothing that could (or should) be done here. I'd suggest to report this upstream on launchpad.net instead.

**Comment by libreajans** [comment]
Yes. Thanks for everything.
